name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: w3c/markup-validator-action@v1
        with:
          file: "index.html"  # Cambia esto según el archivo que quieras validar

  deploy:
    needs: validate-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Publicar en GitHub Pages
        uses: actions/upload-pages-artifact@v2

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v2
